### ISSUE TITLE
Unable to install all packages for WEIS

### ISSUE THREAD

**Issue by Yuksel-Rudy** [WISDEM/WEIS#180]
Hi WEIS developers:
I was following the installation steps, but I'm stuck at installing the pyoptsparse package for some reason. I'm getting this message:

"PackagesNotFoundError: The following packages are not available from current channels:

  - pyoptsparse
Current channels:

  - https://conda.anaconda.org/conda-forge/win-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org"

When I check the packages in my environment, not even other packages were installed. Your help is deeply appreciated. 

Thank you.

**Comment by yonghoonlee** [comment]
I guess pyoptsparse is only available for Mac and Linux. @dzalkind Would it be a good idea to move pyoptsparse to the Mac/Linux specific installation?

**Comment by Yuksel-Rudy** [comment]
oh yes, removing it actually fixed the issue. Thank you @yonghoonlee

**Comment by dzalkind** [comment]
Hi Rudy and Yong Hoon,

Currently, WEIS is only supported for Windows users when using Windows Subsystem Linux.  I'd recommend taking this route.  Otherwise, some of the modules need to be compiled separately and the `setup.py` script will ned to be adjusted.  We are currently working on better Windows documentation.

Best, Dan

**Comment by dzalkind** [comment]
Yong Hoon,

Have you set up WEIS and compiled things on a Windows system?

Best, Dan

**Comment by AthulKrishnaSundarrajan** [comment]
Hi @dzalkind 
I use WEIS on a WSL.

**Comment by Yuksel-Rudy** [comment]
I see what you mean @dzalkind. When running an example, it definitely asks for pyoptsparse.

**Comment by yonghoonlee** [comment]
> Yong Hoon,
> 
> Have you set up WEIS and compiled things on a Windows system?
> 
> Best, Dan

I tried on the bare PowerShell environment before but it was not quite working well. However, I did not try recently. As you mentioned, WSL would be a good place to run WEIS.
