### ISSUE TITLE
Enabling YawDOF for a monopile requires some PtfmYIner

### ISSUE THREAD

**Issue by dzalkind** [WISDEM/WEIS#190]
## Description
Need to set some dummy value for PtfmYIner.  Refer to Roger's email on 9/15/22 for fix.

### Steps to reproduce issue
_Please provide a minimum working example (MWE) if possible_

1. …
2. …
3. …

### Current behavior
…

### Expected behavior
…

### Code versions
_List versions only if relevant_
- Python
- …

**Comment by gbarter** [comment]
Corrected in https://github.com/WISDEM/WEIS/pull/191
