### ISSUE TITLE
Develop branch readme instructions unclear

### ISSUE THREAD

**Issue by DeepFriedDerp** [WISDEM/WEIS#196]
In the readme, step 1 says to setup the conda environment and install some packages, however, the way it is currently written, the following error occurs:

> PackagesNotFoundError: The following packages are not available from current channels: - petsc4py

Upon further inspection of the main branch instructions, a missing command is needed in order to allow conda to install petsc4py:

> conda config --add channels conda-forge

This is included in the main branch readme, but is missing from the develop branch readme.

**Comment by gbarter** [comment]
Thank you, this is fixed now.
