### ISSUE TITLE
No Flap Actuation in WEIS/examples/07_te_flaps example simulation

### ISSUE THREAD

**Issue by DeepFriedDerp** [WISDEM/WEIS#200]
## Description
Develop Branch, example 07_te_flaps appears to be incapable of producing flap actuation as currently set up. 

Found by: 
- Plotting the FAST output (both .out and .outb) for BLFLAP[1 thru 3] for multiple simulation runs. 
- Verifying that the .out columns for BLFLAPs are all 0.000 for all simulation time, for multiple simulation runs. 
- Comparing results for Flp_Mode = 1 and Flp_Mode = 2. If the DLC, avg wind speed, and turbulence seed are the same, then the system response for all states in the .out files are exactly the same, indicating that changing flap control modes doesn't result in a change in flap behavior. 
- Inserting code into ROSCO/ROSCO/src/Controllers.F90 to print out the current LocalVar%Flp_Angle and elements 120-122 of avrSWAP after LocalVar%Flp_Angle is assigned to avrSWAP. This confirmed that flap actuation and assignment of non-zero flap angles to avrSWAP was occuring inside of the FlapControl subroutine, but somehow those changes were not showing up in the .out files or apparently affecting the simulation in any way. 

### Steps to reproduce issue
1. Install from develop branch
2. From WEIS/examples/07_te_flaps, run dac_driver.py to run simulation
3. Validate claims from issue description using the .out and/or .outb files from the 07_te_flaps/temp directory. 

### Current behavior
- BLFLAP[1 thru 3] is 0.000 for all points in output files
- System responses are exactly the same for same DLC, same wind speed, same turbulence seed, different ROSCO Flp_Mode settings. 

### Expected behavior
- BLFLAP[1 thru 3] are non-zero for some portion of time in the simulation .out/.outb files
- System responses should be different for same DLC, same wind speed, same turbulence seeds, different ROSCO Flp_Mode settings, at least within the operating regions that would trigger flap actuation.

**Comment by dzalkind** [comment]
I think `AfCmode` is not being set.  Can you verify this from the OpenFAST inputs?

I would set it around [here](https://github.com/WISDEM/WEIS/blob/d6ac26e2d130a2d244a9702036ef696cb914ee1c/weis/control/tune_rosco.py#L205) with

```self.modeling_options['Level3']['ServoDyn']['AfCmode'] = 5```

Sorry, I am not set up with XFoil or working on flap control much, so I might not be able to provide a lot of good support/testing for this.

**Comment by DeepFriedDerp** [comment]
@dzalkind, this fixed the problem! 

I'd recommend committing the change you suggested, because I don't think example 07 will work properly without it. 

Thanks so much!

**Comment by DeepFriedDerp** [comment]
This issue has been open for a while, so I'll add a new issue that I ran into while working with this example.

In BAR_USC_flaps.yaml, under components/blade/aerodynamic_control/te_flaps, the span_start and span_end are very close to each other (0.7 and 0.71, respectively). When I was running examples comparing the different flap modes, I was getting no discernible difference in turbine response, despite the very different blade flap behavior (the plots of tip deflection and root bending moments were visually identical). 

@Ben-Mertz figured out this was the cause of the apparent lack of turbine response, and has verified that increasing the amount of span occupied by the te flaps does produce a more noticeable response. Because this is an example, meant to demonstrate to a new user how to integrate te flaps into their model, it may be a good idea in a future commit to increase the initial span of the te flaps in the BAR_USC_flaps.yaml

**Comment by ptrbortolotti** [comment]
PR #213 should help close this issue
