### ISSUE TITLE
Minimum system requirements

### ISSUE THREAD

**Issue by mlidGWT** [WISDEM/WEIS#222]
Hello, 

Inexperienced coder/GitHub user here, so please excuse any missing information or basic language (and keep any questions/answers dumbed down, please!). 

I am trying to set up the WEIS develop branch on a WSL using Conda version 23.1.0, Python version 3.10, on a Windows 10 machine with 16GB RAM. The 'Solving environment' step of the `conda env create --name weis-env -f https://raw.githubusercontent.com/WISDEM/WEIS/develop/environment.yml` command keeps getting killed. I finally tried with only the WSL and Task Manager open to minimize memory use and see what's happening (no changes to backend functions), and saw that a couple minutes into the process, the memory is around 81% utilization, but the Disk capped out from the 'System' process and shortly thereafter the process was Killed. 

I have tried running the command from Issue #171 without the pyoptsparse item, and it completed successfully. I have also then tried running the same command with only the pyoptsparse item and it also completed successfully, so that does not seem to be where the issue is, on the surface. 

Are there minimum system requirements for this package that my computer doesn't meet, or is something else happening? I have hit the limits of my troubleshooting capabilities given the lack of any useful error message. Any thoughts on what's going wrong?

**Comment by gbarter** [comment]
I would try all of the `conda` commands with `mamba` and see if that solves things:
https://mamba.readthedocs.io/en/latest/installation.html

We might need to consider making that switch in our instructions. . .
