### ISSUE TITLE
New Turbulence Model for AEP Calculations

### ISSUE THREAD

**Issue by ptrbortolotti** [WISDEM/WEIS#228]
WEIS currently uses DLC 1.1/1.2 for AEP calculations. 

DLC 1.1/1.2 uses the Normal Turbulence Model, which includes a turbulence standard deviation for the 90% quantile. 

Therefore, the NTM as defined by IEC is still harsher turbulence than we would expect for a site that is characterized as ‘A’, ‘B’, ‘C’, etc.  

WEIS could consider to use a new DLC for AEP calculations only, one that represents 50% quantile turbulence distribution. The new calculation will give more favorable results and would be more realistic.

The suggestion comes from the BAR external advisory board

**Comment by dzalkind** [comment]
The AEP DLC has been implemented in the `develop` branch with #308
