### ISSUE TITLE
How can I add multiple breakpoints in WEIS?

### ISSUE THREAD

**Issue by khc4156** [WISDEM/WEIS#230]
Hello, 

Thank you for your time always. 

Now I am following the paper below with WEIS. 

Zalkind, D., Abbas, N.J., Jasa, J., Wright, A. and Fleming, P., 2022, May. Floating wind turbine control optimization. In Journal of Physics: Conference Series (Vol. 2265, No. 4, p. 042021). IOP Publishing.

In the paper, there is an explanation of the multiple breakpoints to define natural frequency (omega) and damping ratio (zeta). 
I want to practice this in WEIS, but I couldn't find which input option is related to this. 

Can you let me know which input option I can add or change for using the different number of breakpoints in WEIS?

Thank you.

HC Kim

**Comment by dzalkind** [comment]
No, sorry :-) 

This is it: https://github.com/WISDEM/WEIS/blob/e5e124c7e2340f4392127ba40f256486d5f97d40/examples/02_control_opt/modeling_options.yaml#L93

**Comment by wind2021** [comment]
Dear Daniel, 
Thank you for all your help. I have two questions. 
As shown in the figure below, in the simulation results obtained by running **02_control_opt** with statements（python weis_driver.py）, I found that my iterations were small，just 1 iteration？ Should I change parameters such as **max_major_iter**、**max_minor_iter**、**max_iter** all to 100 to get the Figure 2 result？
What should I do if I want to use this method for NREL 5MW_OC4_semi turbine？
![image](https://github.com/WISDEM/WEIS/assets/76504585/a9b70b1d-3353-4ddf-97b8-666de9707ee9)
![image](https://github.com/WISDEM/WEIS/assets/76504585/16b89754-1330-4b5d-801b-1700cbd4e339)

Best Regards
Lei Xue

**Comment by dzalkind** [comment]
Change `max_iter` to increase the iterations.  However, it depends on the specific solver, so you may need to try them out if you change the solver.

**Comment by wind2021** [comment]
Thank you！I just change the max_iter and it runs well. 
But can you give me some advice about how to use this method for **NREL 5MW_OC4_semi** turbine model？As there is only **IEA-15-240-RWT-UMaineSemi** turbine model in **example 02_control_opt**

**Comment by dzalkind** [comment]
If you already have an OpenFAST model for the NREL_5MW_OC4_semi, you can assign it in the modeling options of the `02_control_opt` example.

Alternatively, the `04` example will generate an OpenFAST model from the geometry input provided in that example.  You can use the same (or similar) analysis options in that example as in the `02` example you have been using.

**Comment by dzalkind** [comment]
It looks like the library for pyframe3dd is missing.  This library is generated during the installation of WISDEM.  You can navigate to the `WISDEM/` directory and run `python setup.py develop` there.  Please share any errors you see and any setup logs within the `WISDEM/build` directory.

**Comment by wind2021** [comment]
<img width="942" alt="1695306164089" src="https://github.com/WISDEM/WEIS/assets/76504585/1114d7f1-fd63-44df-8d4a-f8461d1a5655">
<img width="659" alt="1695306203057" src="https://github.com/WISDEM/WEIS/assets/76504585/87811f28-d49d-42a4-86a3-7f08fe40b7f3">
<img width="702" alt="1695306274515" src="https://github.com/WISDEM/WEIS/assets/76504585/5c5eedb9-527c-4c0e-9913-429418dadd3e">
<img width="714" alt="1695306313468" src="https://github.com/WISDEM/WEIS/assets/76504585/a4ac03bd-af4c-4ccc-b0ec-9573d6e34cee">

As you can see this. What should I do?

**Comment by wind2021** [comment]
<img width="696" alt="1695306593045" src="https://github.com/WISDEM/WEIS/assets/76504585/d5b87208-bf4a-4de8-a51f-e1ee2c829197">
Is this the  pyframe3dd ?

**Comment by dzalkind** [comment]
If you're using a branch that used meson, which it seems like you are, there should be a `WISDEM/meson_build/setup.log` file with more information.

**Comment by wind2021** [comment]
<img width="714" alt="1695306767309" src="https://github.com/WISDEM/WEIS/assets/76504585/864537cb-6c4a-4bd6-a791-f214f5b22993">
In fact, I initially installed WSL on disk C and later moved to disk D. Whether it makes a difference?

**Comment by dzalkind** [comment]
Try deleting the `meson_build` directory, any previous `build` directories in `WISDEM/`, and `WISDEM/WISDEM.egg-info`, then try `python setup.py develop` again.

**Comment by wind2021** [comment]
<img width="945" alt="1695307725747" src="https://github.com/WISDEM/WEIS/assets/76504585/4341c2f7-7c9d-4d80-ba88-98943eacde6f">
Thank you very much！Now the example 04 runs successfully, but when I put the output file **refturb_output.yaml**  to 02_control_opt and run example 02, it appeared RuntimeError: 'wisdem.wt.floatingse.load.frame' as the picture.  What should I do now?
