### ISSUE TITLE
DISCON.IN output of example 05

### ISSUE THREAD

**Issue by alexandermoennig** [WISDEM/WEIS#233]
Hi,
I am currently working with the example 05 on the develop branch and noticed some discrepancies between the controller output (DISCON.IN) generated by WEIS and the one provided in the repository of the RWT.
Using the ROSCO toolbox and both DISCON.IN files, I generated the following plot:
![image](https://github.com/WISDEM/WEIS/assets/76425193/ffd4b1f5-193e-4bab-8ba0-5b99028add77)
My question is whether these differences are expected when using WEIS, or if there's a possibility to correct them?

Thanks in advance.
Kind regards,
Alex

**Comment by dzalkind** [comment]
Hi Alex,

These min pitch tables depend on the Cp, Ct surfaces.  They are set up in WEIS to be very coarse, which usually leads to controller issues.

In the modeling options, you should set:
`n_tsr_perf_surfaces: 25`
`n_pitch_perf_surfaces: 25`

I hope this helps.

Best, Dan

**Comment by alexandermoennig** [comment]
Hi Dan,

yes, that helped. Looks perfect now:
![image](https://github.com/WISDEM/WEIS/assets/76425193/542d734c-3f43-4a55-81d4-5fdfbfb77a0a)
Thank you very much for your help :) 

Kind regards,
Alex
