### ISSUE TITLE
Incorrect OpenFAST version dependency in README

### ISSUE THREAD

**Issue by mlidGWT** [WISDEM/WEIS#236]
## Description
I'm trying to figure out what version of OpenFAST is being used in the latest WEIS/develop branch, but the README is incorrect. I would suggest updating the README to indicate that version 3.5.0 is needed.

### Steps to reproduce issue
I am trying to determine what version of OpenFAST is used within WEIS to troubleshoot an error I am getting, and the README indicates version 3.4.0 is used: [Packages](https://github.com/WISDEM/WEIS/tree/develop#packages)

However, the openfast submodule indicates that it's version 3.5 via this line in the documentation: [Line 131](https://github.com/WISDEM/WEIS/blob/develop/OpenFAST/docs/conf.py#L131)

### Code versions
- dev branch @ https://github.com/WISDEM/WEIS/commit/2dd692a019ee01a3cd69e5b60819b12de002d606

**Comment by dzalkind** [comment]
Thanks for the heads up, it's been updated.

Dan
