### ISSUE TITLE
Strange Nodal Outputs behavior

### ISSUE THREAD

**Issue by mlidGWT** [WISDEM/WEIS#243]
## Description
Hello, I think this question is best directed towards @mayankchetan, but if anyone else has ideas I'm all ears! (eyes?)

I recently ran some simulations with nodal outputs enabled in ElastoDyn (ED) and AeroDyn (AD), and I'm getting some odd outputs. I am running WEIS, but with the openfast directory, as in Example 02. 

In ED, I had defined a list of 29 blade gages (`NBlGages`), more or less evenly distributed along the 60 stations of the IEA reference turbine's blade. In the nodal outputs section, I had asked for outputs from all 3 blades, and since `BldNd_BlOutNd` does not yet seem to be implemented, left 60, so it would default to all nodes if that was being used in some way. In the regular outlist, I removed the Spanwise sensors, since I was expecting nodal outputs anyway. I also removed the tower section outputs, since I am not interested in detailed tower analysis from this simulation. 

In the resulting .out file, not only were the removed spanwise and tower station sensors still present, only for nodes 0-9, but the nodal outputs provided were only for nodes 1 through 50, so I have no idea what stations they correspond to. I can confirm that the WEIS-written ED_blade.dat file shows 60 stations, and my ED.dat file has the `NBlGages` as I had defined them, though also includes the removed spanwise and tower section sensors. 

A similar thing is happening with AD, so I will spare the details. 

Please let me know if this should be moved to the Discussions page - I'm having trouble distinguishing between user error (which would go in Discussions) and bugs, though this feels like a bug.

### Steps to reproduce issue
I am using the IEA 15MW RWT, with modifications made only to the outputs requested. This folder is my `openfast_dir` as specified in my `modeling_options.yaml`: 
[IEA15_GWTBaseline.zip](https://github.com/WISDEM/WEIS/files/13179021/IEA15_GWTBaseline.zip)
Note that the AD.dat and ED.dat files have nodal outputs enabled and are the main focus for this issue.

My WEIS input files: 
[WEIS_Inputs.zip](https://github.com/WISDEM/WEIS/files/13179060/WEIS_Inputs.zip)

The WEIS-written AD, AD_blade, ED, and ED_blade.dat files: 
[WEIS-writtenFiles.zip](https://github.com/WISDEM/WEIS/files/13179090/WEIS-writtenFiles.zip)

My Out file is I think too big to share, but here is a CSV with the column names from the Python dataframe it makes: 
[all_columns.csv](https://github.com/WISDEM/WEIS/files/13179077/all_columns.csv)

Please let me know if any other files are needed. 

### Current behavior
1. The WEIS-written AeroDyn.dat file has added the B[1-3]N[1-9]Alpha outputs, despite not being in the input/seed AeroDyn.dat file and "Alpha" being one of the nodal outputs requested 
2. The output nodes (for both AD and ED outputs) are for nodes 1-50, despite both the input and WEIS-written blade files clearly having 60 nodes, and the node list defined in the ED and AD.dat files containing 29 and 25 nodes, respectively.
3. I have no way to determine which of the 60 stations are being represented by the 50 nodal outputs, so these results are unusable to me. 

### Expected behavior
1. The Blade Alpha outputs should not reappear outside of the Nodal Outputs section, since they weren't defined in the general OutList
2. The nodal outputs should either A) match the nodes I defined in `BlOutNd` and `BldGagNd`, respectively, or B) provide nodal outputs for all of the stations defined in the corresponding _blade.dat files.
3. It may be a good idea to add an automatic output (perhaps just a small, additional output file, rather than within the .out file itself) to decode the output nodes with the defined blade stations, whenever nodal outputs are used, to help avoid this type of confusion even after fixing the above issues. 

### Code versions
- WEIS develop, recently pulled (within October)

**Comment by dzalkind** [comment]
@mayankchetan, is this a WEIS issue or something that should be addressed in OpenFAST?
