### ISSUE TITLE
Issues when performing optimization examples

### ISSUE THREAD

**Issue by Russell9798** [WISDEM/WEIS#250]
Hi,

I'm trying to run the example optimization of 03_NREL5MW_OC3_spar but I get the following errors when trying to run the example with the set design variables and constraints.

1. "DerivativesWarning:Constraints or objectives [wisdem.wt.floatingse.sys.mux.platform_mass] cannot be impacted by the design variables of the problem because no partials were defined for them in their parent component(s)"

2. "RuntimeError: ScipyOptimizeDriver: Constraint 'aeroelastic.rotor_overspeed' does not depend on any design variables. Please check your problem formulation."

I'm hoping to understand what these mean, what's causing them and how I can fix them. The second error can be removed if I set all of the constraints to False in the analysis_options.yaml file, but I'd prefer not to do this. The same errors appear when trying to run optimization of 06_IEA-15-240-RWT.

Many thanks,

Andrew

**Comment by gbarter** [comment]
Hi Andrew,

I think you can safely ignore those warnings.  Some of the objectives and constraints are long vectors with some bounds on one or both ends.  Think of the blade chord with a locked blade root size.  There are other similar examples.  The messages you saw is the OpenMDAO library coming to the same conclusion.  No need to change any settings.

Cheers,
Garrett
