### ISSUE TITLE
Fatal openfast error in the examples/15_RAFT_Studies/weis_driver_level3.py

### ISSUE THREAD

**Issue by Wying301** [WISDEM/WEIS#255]
Hi, 

I try to understand WEIS as DLC analysis tool by running the example 15_RAFT_Studies/weis_driver_level3.py. But OpenFAST Failed to run and I receive the following errors:
`FAST_InitializeAll:ED_Init:ED_ReadInput:ReadTowerFile:TwSSM2Sh: value is not a finite real number.`
`OpenFAST encountered an error during module initialization.
  Simulation error level: FATAL ERROR`
`Aborting OpenFAST.`
`OpenFAST Failed: Command '['/Users/WEIS/local/bin/openfast', 'IEA15_3.fst']' returned non-zero exit status 1.`
`OpenFAST Failed! Please check the run logs.`
`OpenFAST failures are allowed. All outputs set to 9999`

It seems that the tower file from ElastoDyn has some problem. So I check the file IEA15_0_ElastoDyn_tower.dat, and found some values are "nan" (see below).
![image](https://github.com/WISDEM/WEIS/assets/57876661/2a79f52c-d396-45b7-bd7c-f0bce9917294)

Can you help to fix this problem? Thanks!

**Comment by dzalkind** [comment]
This should be fixed with the latest release
