### ISSUE TITLE
How to Open the Optimization Log File (log_opt.sql) in WEIS

### ISSUE THREAD

**Issue by hymdrj** [WISDEM/WEIS#297]
Hello,

I am studying the RAFT-based WEIS (Level 1) program that allows optimization of floating body specifications. I have three questions while reviewing this optimization program:

1. I understand that the file recorded during the optimization process is saved in log_opt.sql, but I have tried various methods to open this file and confirmed that text was broken. I am curious about how to open the log_opt.sql file.

2. The optimization algorithm proceeds with optimization through several iterations, and I am curious about how to determine whether the optimization has progressed well without falling into a local area.

3. Lastly, I would like to know where the motion response results for each floating body are stored for each iteration. If not, I would like to know which part of the WEIS code needs to be modified.

Thank you for reading.

**Comment by dzalkind** [comment]
This notebook shows how to open the log_opt.sql files: https://github.com/WISDEM/WEIS/blob/main/examples/16_postprocessing/rev_Opt.ipynb

Each WEIS run has the final openmdao input/output information saved in a csv file.  Anything with a `raft.` should include the RAFT outputs.  You can enable that information to be saved for each iteration using the `recorder` in openmdao like this: https://github.com/WISDEM/WEIS/blob/77512f2244be4e445425b107c4c40d67326cfaed/examples/15_RAFT_Studies/analysis_options.yaml#L86
