### ISSUE TITLE
Mismatch between tabular data and technical report plots 

### ISSUE THREAD

**Issue by hth06** [WISDEM/WEIS#299]
## Description
The thrust curve of the rotor performance plot in page 19 of the IEA Wind TCP Task 27 technical report does not match the tabular Thrust data found in the 'IEA-15-240-RWT_tabular' Excel file in the Documentation folder. Which is the correct data?

**Comment by gbarter** [comment]
Please see: https://github.com/IEAWindTask37/IEA-15-240-RWT/wiki/Frequently-Asked-Questions-(FAQ)
"Why do the simulated VolturnUS-S properties differ from the report?"
