### ISSUE TITLE
Difficulty running WEIS on WSL

### ISSUE THREAD

**Issue by ailsamcmillan1** [WISDEM/WEIS#318]
Hi,

I have followed the installation guidance on https://github.com/WISDEM/WEIS/ to download WEIS using WSL, and I seem to successfully be able to run the ~WEIS/weis/test/run_examples.py

However, when i try to run an example in WEIS/examples/ I am getting an error (copied below).

I have tried copying example files that have worked for other people but I keep getting this same error. I have tried examples from 05 and 06. Any help getting the files running would be appreciated!

Best wishes,
Ailsa 

Error message and command:
(weis-env) ailsamcmillan@ENG-7894:~/WEIS/examples/05_IEA-3.4-130-RWT$ python weis_driver.py
Using weis.aeroelasticse in rosco.toolbox...
Traceback (most recent call last):
  File "/home/ailsamcmillan/WEIS/examples/05_IEA-3.4-130-RWT/weis_driver.py", line 15, in <module>
    wt_opt, modeling_options, opt_options = run_weis(fname_wt_input, fname_modeling_options, fname_analysis_options)
                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/ailsamcmillan/WEIS/weis/glue_code/runWEIS.py", line 165, in run_weis
    wt_opt.setup(derivatives=False)
  File "/home/ailsamcmillan/miniforge3/envs/weis-env/lib/python3.12/site-packages/openmdao/core/problem.py", line 1067, in setup
    self._check_collected_errors()
  File "/home/ailsamcmillan/miniforge3/envs/weis-env/lib/python3.12/site-packages/openmdao/core/problem.py", line 643, in _check_collected_errors
    raise RuntimeError('\n'.join(final_msg))
RuntimeError:
Collected errors for problem 'weis_driver':
   <model> <class WindPark>: Attempted to connect from 'aeroelastic.hub_Fxyz' to 'drivese_post.F_hub', but 'drivese_post.F_hub' doesn't exist. Perhaps you meant to connect to one of the following inputs: ['drivese_post.hub_I', 'drivese_post.F_mb2', 'drivese_post.F_mb1'].
   <model> <class WindPark>: Attempted to connect from 'aeroelastic.hub_Mxyz' to 'drivese_post.M_hub', but 'drivese_post.M_hub' doesn't exist. Perhaps you meant to connect to one of the following inputs: ['drivese_post.hub_I', 'drivese_post.M_mb2', 'drivese_post.M_mb1'].

**Comment by dzalkind** [comment]
Hi, this looks like an issue with the newest version of WISDEM.  We're addressing that in this PR: #317.

A few of the examples still need to be fixed, but the connection issue you raised should have been addressed.
