### ISSUE TITLE
Implement automated testing through GitHub actions

### ISSUE THREAD

**Issue by johnjasa** [WISDEM/WEIS#6]
Can borrow a lot from OpenFAST for the time being.
This needs to happen in tandem with architecting meaningful tests.

**Comment by gbarter** [comment]
Can you send the link to the error?

**Comment by ptrbortolotti** [comment]
https://github.com/WISDEM/WEIS/runs/1245741799?check_suite_focus=true

**Comment by gbarter** [comment]
Is pyoptsparse needed for the tests?  Could probably just put a try/except: pass around the setup call [there](https://github.com/WISDEM/WEIS/blob/master/setup.py#L95), right?
