### ISSUE TITLE
NLinTimes not Respected

### ISSUE THREAD

**Issue by ptrbortolotti** [WISDEM/WEIS#99]
## Description
When the Linearize and the TrimCase flags are turned on, the Python call to OpenFAST does not respect the NLinTimes input, and runs never-ending linearization

### Steps to reproduce issue

1. Compile this repo https://github.nrel.gov/pbortolo/BDstab
2. Change this WS to be nonzero (say 5 m/s) https://github.nrel.gov/pbortolo/BDstab/blob/0476fa12a34fa0b9ecaaf82d7fb13fb5f0dff1dd/run_OF/BAR0_ED.py#L24
3. Run this script https://github.nrel.gov/pbortolo/BDstab/blob/master/run_OF/BAR0_ED.py
4. OF will not stop at NLinTimes 12 https://github.nrel.gov/pbortolo/BDstab/blob/0476fa12a34fa0b9ecaaf82d7fb13fb5f0dff1dd/run_OF/BAR0_ED.py#L30
5. Kill the job and run the .fst with a system call to OF from a terminal
6. OF will stop after 12 linearization

### Current behavior
The python call to OF is broken

### Expected behavior
OF runs the requested number of linearization

### Code versions
Latest WEIS develop

**Comment by rafmudaf** [comment]
@ptrbortolotti see https://github.com/rafmudaf/openfast/tree/feature/python_driver

**Comment by dzalkind** [comment]
This is working for both the OpenFAST executable and library
